### ISSUE TITLE
.NET Framework 4.0 support

### ISSUE THREAD

**Issue by csjune** [PureKrome/NLog.Bugsnag#4]
Hi, PureKrome

Do you have any plan to support .NET Framework 4.0? I want to use `NLog.Bugsnag` but my project is based on .NET Framework 4.0 for Windows XP support.

Thanks,
csjune

**Comment by PureKrome** [comment]
Nope - not really. Mainly because `async/await` is not baked into .NET 4.0. With 4.0 I'll need to add an extra nuget package [Microsoft.Bcl.Async/](https://www.nuget.org/packages/Microsoft.Bcl.Async/) which suddenly makes the project a lot more work.

I'm happy to review any PR's for this, but as for ~me~ spending cycles on it - nope.

My condolences for having to work with Windows XP still.
